### ISSUE TITLE
Failure to move DMC-30019

### ISSUE THREAD

**Issue by bleaktwig** [motorapp/Galil-3-0#14]
Hi,
We are having an issue when sending commands to a Galil single-axis DMC-30019 controller. After setting up the software and establishing a connection with the controller, we fail to send commands to it via `caput`. Running the `trajectoryA.sh` script provided, the motor fails to move and we get two warnings: `The requested data transfer is greater than available memory or EPICS_CA_MAX_ARRAY_BYTES` and `Identical process variable names on multiple servers`. The full log is in the [log_trajectoryA.txt](https://github.com/motorapp/Galil-3-0/files/8689213/log_trajectoryA.txt) file.

Simply trying `caput DMC01:Prof1:M1Positions 1500` gives only the second warning, but also fails to move the motor. The full log is in the [log_caput.txt](https://github.com/motorapp/Galil-3-0/files/8689216/log_caput.txt) file.

About the second warning, we set up the IP by enabling DHCP using the `DH0` command and then the `IA ip_addr` command.

We are able to move the motor normally through GDK and by sending commands from the terminal via serial-to-USB and via ethernet, so it seems that the issue itself lies in the EPICS software. We also tried both the 3-1 and the 3-6 versions of the motorapp and both present the same issue.

We're unsure on how to continue, so any help or advice would be useful.

**Comment by motorapp** [comment]
Hi Bruno,
The reported issue is not a problem in the Galil EPICS driver, but is a property of the EPICS channel access protocol.
The notification about the same process variable on multiple servers is most likely because the IOC is executed on a machine with multiple LAN interfaces.  EPICS will work on machines with multiple network interfaces and the message can safely be ignored.
Please set the EPICS_CA_MAX_ARRAY_BYTES as an environment variable to allow data transfers of larger size.  
On linux put the below line in the home directory .bashrc file:
export EPICS_CA_MAX_ARRAY_BYTES 9999999
On Windows set EPICS_CA_MAX_ARRAY_BYTES as an environment variable.

Whilst becoming familiar with the Galil EPICS driver it is recommended to use MEDM or QT EPICS, and the screens provided with the Galil EPICS driver, as there are many PV's in the database.  It can be confusing initially.
To run a trajectory/profile the workflow = transfer the profile data, build and verify, then finally execute. (3 steps)
Please email padmoz@tpg.com.au for further assistance.
Kind regards,
Mark
